name: PR Checks

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [10.x, 12.x]

    runs-on: ubuntu-latest

    # This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
    # For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    
    - name: Cache yarn dependencies
      uses: actions/cache@v1
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run : yarn
    
    - name: Test with Jest    
      uses: hwasurr/jest-reporter-action@v0.0.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        test-command: "yarn jest --coverage"

    - name: Build with webpack
      run : yarn build





